table d_artists
	lineageTag: 01f56fe4-8814-4e88-bce8-9dc82712c0e5

	column ArtistId
		dataType: int64
		formatString: 0
		lineageTag: 777d8913-738c-4586-a43b-61fa7a380dde
		summarizeBy: none
		sourceColumn: ArtistId

		annotation SummarizationSetBy = Automatic

	column ArtistName
		dataType: string
		lineageTag: 6fac6df9-6c85-491c-8c72-bf25157a1d7c
		summarizeBy: none
		sourceColumn: ArtistName

		annotation SummarizationSetBy = Automatic

	partition d_artists = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(dir_source_data & "artists.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ArtistId", Int64.Type}, {"Name", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "ArtistName"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

